"""add OCR fields to transactions

Revision ID: 70bcd2ff1ac7
Revises: 
Create Date: 2026-05-25 15:20:05.945543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bcd2ff1ac7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('receipt_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ocr_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('ocr_text')
        batch_op.drop_column('receipt_image')
        batch_op.drop_column('merchant')

    # ### end Alembic commands ###
