#!/bin/bash
set -e

# ============================================================
# AI Accounting System — Production Deployment Script
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# --- Check prerequisites ---
info "Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    error "Docker is not installed. Install it first: https://docs.docker.com/get-docker/"
fi

if ! docker compose version &> /dev/null; then
    error "Docker Compose V2 is not available."
fi

info "Docker $(docker --version | awk '{print $3}')"
info "Docker Compose $(docker compose version --short)"

# --- Check .env.production ---
if [ ! -f .env.production ]; then
    warn ".env.production not found, creating from template..."
    cp .env.production .env.production.bak 2>/dev/null || true

    # Generate random secrets
    SECRET_KEY=$(openssl rand -hex 32)
    JWT_SECRET_KEY=$(openssl rand -hex 32)
    FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || openssl rand -base64 32)
    MYSQL_ROOT_PASSWORD=$(openssl rand -hex 16)
    MYSQL_PASSWORD=$(openssl rand -hex 16)

    cat > .env.production << EOF
# Auto-generated by deploy.sh on $(date)
SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
FERNET_KEY=${FERNET_KEY}

MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
MYSQL_DATABASE=ai_accounting
MYSQL_USER=ai_user
MYSQL_PASSWORD=${MYSQL_PASSWORD}
MYSQL_EXPORTER_PASSWORD=$(openssl rand -hex 12)

REDIS_PASSWORD=$(openssl rand -hex 16)
ADMIN_PASSWORD=$(openssl rand -hex 16)

DEEPSEEK_API_KEY=
CORS_ORIGINS=https://your-domain.com
FRONTEND_URL=https://your-domain.com
STORAGE_PROVIDER=local
LOG_LEVEL=INFO
SENTRY_DSN=
GRAFANA_USER=admin
GRAFANA_PASSWORD=$(openssl rand -hex 12)
RATELIMIT_STORAGE_URI=redis://redis:6379
EOF

    info ".env.production created with random secrets."
    echo ""
    echo "  ╔══════════════════════════════════════════════╗"
    echo "  ║  Generated Credentials (SAVE THESE!)         ║"
    echo "  ╠══════════════════════════════════════════════╣"
    echo "  ║  Admin password: $(grep ADMIN_PASSWORD .env.production | cut -d= -f2)"
    echo "  ║  Grafana login:  admin / $(grep GRAFANA_PASSWORD .env.production | cut -d= -f2)"
    echo "  ╚══════════════════════════════════════════════╝"
    echo ""
    warn "Edit .env.production to set DEEPSEEK_API_KEY, CORS_ORIGINS, FRONTEND_URL, SENTRY_DSN"
fi

# --- SSL certificates ---
if [ ! -f nginx/ssl/cert.pem ] || [ ! -f nginx/ssl/key.pem ]; then
    warn "SSL certificates not found in nginx/ssl/"
    echo ""
    echo "Options:"
    echo "  1) Use self-signed certificate (development/testing)"
    echo "  2) Use Let's Encrypt (production — requires domain)"
    echo "  3) Skip (place certificates manually later)"
    echo ""
    read -p "Choose [1/2/3]: " ssl_choice

    case $ssl_choice in
        1)
            info "Generating self-signed certificate..."
            mkdir -p nginx/ssl
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
                -keyout nginx/ssl/key.pem \
                -out nginx/ssl/cert.pem \
                -subj "/C=CN/ST=Beijing/L=Beijing/O=AI Accounting/CN=localhost" \
                2>/dev/null
            info "Self-signed certificate created."
            ;;
        2)
            info "For Let's Encrypt, run:"
            echo "  apt install certbot"
            echo "  certbot certonly --standalone -d your-domain.com"
            echo "  cp /etc/letsencrypt/live/your-domain.com/fullchain.pem nginx/ssl/cert.pem"
            echo "  cp /etc/letsencrypt/live/your-domain.com/privkey.pem nginx/ssl/key.pem"
            exit 0
            ;;
        3)
            warn "Skipping SSL setup. Place cert.pem and key.pem in nginx/ssl/ before starting."
            ;;
    esac
fi

# --- Symlink .env.production to .env for docker compose interpolation ---
if [ -f .env.production ]; then
    cp .env.production .env
    info ".env.production -> .env (for compose interpolation)"
fi

# --- Build and start ---
info "Building and starting services..."
docker compose -f docker-compose.prod.yml --env-file .env.production build --no-cache
docker compose -f docker-compose.prod.yml --env-file .env.production up -d

# --- Wait for health ---
info "Waiting for services to become healthy..."
sleep 15

# --- Check status ---
info "Service status:"
docker compose -f docker-compose.prod.yml ps

echo ""
info "🎉 Deployment complete!"
echo ""
echo "  Application:    https://localhost"
echo "  Prometheus:     http://localhost:9090  (localhost only)"
echo "  Grafana:        http://localhost:3000  (localhost only)"
echo "  Kibana:         http://localhost:5601  (localhost only)"
echo ""
echo "  Default Grafana login: admin / (see .env.production)"
echo ""
